'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

total_sum = 2
previous_fib = 1
current_fib = 2
while current_fib + previous_fib < 4000000:
    if ((current_fib + previous_fib) % 2) == 0:
        total_sum += (current_fib + previous_fib)
    temp = previous_fib
    previous_fib = current_fib
    current_fib = current_fib + temp

print(total_sum)